#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1.5
bspc config window_gap          7

bspc config focused_border_color "#E33636"
bspc config normal_border_color "#BF2C2C"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a "Volume Control" desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a pavucontrol state=floating follow=on
bspc rule -a pcmanfm state=floating
bspc rule -a neovide state=monocle
