require('plugins')
require('treesitter-config')
require('options')
require('lualine-config')
require('bufferline-config')
require('nvim-tree-config')
require('autopairs-config')
require('telescope-config')
require('keybindings')
require('whichkey-config')
require('cmp-config')
require('lsp')
-- require('dashboard-config')
-- require('colorizer-config')
require('alpha-config')

vim.cmd('colorscheme tokyonight-night')
vim.cmd('set number')
vim.cmd('set noshowmode')
